# Generated by Django 4.1.3 on 2022-11-02 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('OFFICE', 'Офис'), ('STOCKROOM', 'Склад'), ('CONVEYOR', 'Конвейер'), ('WORKSHOP', 'цех')], max_length=50)),
                ('head_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_server.department')),
            ],
        ),
    ]
