# Generated by Django 4.1.3 on 2022-11-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.CharField(max_length=50, verbose_name='Место рождения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterField(
            model_name='department',
            name='head_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_department', to='web_server.department', verbose_name='Головной отдел'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('OFFICE', 'Офис'), ('STOCKROOM', 'Склад'), ('CONVEYOR', 'Конвейер'), ('WORKSHOP', 'цех')], default='OFFICE', max_length=50, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='web_server.employee', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('BOSS', 'Директор'), ('CHiEF', 'Начальник'), ('MANAGER', 'Менеджер'), ('SPECIALIST', 'Специалист'), ('EXPERT', 'Эксперт'), ('INTERN', 'Стажёр')], max_length=50, verbose_name='Должность')),
                ('hire_date', models.DateField(verbose_name='Дата устройства')),
                ('dismiss_date', models.DateField(null=True, verbose_name='Дата увольнения')),
                ('salary', models.PositiveIntegerField(verbose_name='Оклад')),
                ('bonus', models.PositiveIntegerField(verbose_name='Премия %')),
                ('chief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_employees', to='web_server.employee', verbose_name='Начальник')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='web_server.department', verbose_name='Отдел')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='web_server.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
    ]
